version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  dep:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ checksum "package.json" }}
      - run:
          name: Build 
          command: npm run build
  deploy_dev:
     machine:
       enabled: true
     steps:
       - run:
           name: Deploy Over SSH WITHOUT VPN
           command: |
             scp -r /home/circleci/project/dist/* $SSH_USER@$SSH_HOST:~/resource/nextjs-circleci/dist
workflows:
   version: 2
   build-and-deploy:
     jobs:
       - dep
       - build:
          requires:
          - dep
       - deploy_dev:
          requires:
          - build